#!/bin/bash
trap '' 2 
hname=$(head -n 1 ./hostname.txt)
usrprompt="spscwby@"
apos=":"
cmdprompt=$usrprompt$hname$apos


read -p $cmdprompt input

case $input in

	"LEARN")
		bash ./LEARN 
		;&
	"LOAD")
		bash ./load 
		;&
	"REBOOT")
		sleep 2
		bash ./terminalscript
		;&
	"MOTD")
		shuf -n 1 ./motd.txt | fmt -w 83 | pv -qL 90
		bash prompt
		;&
	"DISINTEGRATE")
		exit 1
		;&
	*)
		echo -e "COMMAND UNRECOGNISED" | pv -qL 90
		sleep 2
		bash ./prompt
		;;
esac
trap 2